version: "3.4"

services:

  codebox_server_dev:
    build:
      context: .
      dockerfile: Dockerfile_server
      target: build
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/yuhui/codebox:/codebox
    expose:
      - "5002"
    ports:
      - "5002:5002"
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 5002 --reload
    stdin_open: true
    tty: true

    environment:
      - ENV_FLAG=DEV
      - CODEBOX_ROOT_PATH=/home/yuhui/codebox
    networks:
      - app_network_for_codebox
      
networks:
    app_network_for_codebox:
      external: True
